### PR TITLE
Speedup loop_ecology that was too slow for the evol simulation

### PR DESCRIPTION
**Pull request by ZHG2017**
Hi, I have made the exact improvement in the loop_ecology() function from the ecology.R, which will improve the performance for the evol simulations where the last for loop to construct species_list was identified as a bottleneck.

### CODE REVIEW

**Review by ohagen — APPROVED** [review]
Seams to describe the described speed up and be compatible with reported unit test on species list and richness plotting objects.

**Comment by ZHG2017** [comment]
@[benj919](https://github.com/benj919)  Hi, Sorry to have forgotten to mention that only several evol simulations(~20) are really slow with  the original implementation, the modified part becomes somehow a bottleneck only with one of those evol landscape configurations, like the l12421th andscapes config file, and it becomes really slow only after about 200 iterations, at the very beginning it is still fast enough.
PS: The evol simulation with the 12421th landscapes configuration could not end in 48 hours.

**Comment by ZHG2017** [comment]
The one I used for the number 12421 has a parameter as max_number_of_species = 200000, I used the files provided by [ohagen](https://github.com/ohagen), and I do not have a profiling trace for the current implementation because the concerned simulation does not seem to be able to finish in 48 hours. By the way, I wonder if it is just an error of typing, the test2 function does not seem to return any think meanwhile the test function returns the species_list in your comment.

**Comment by benj919** [comment]
I have added the explicit return statement to test2. If there's none R will (silently) return the last object accessed in a function.

Do you have any profiling data for your simulations? Simulations with a lot of species routinely run for a long time. How did you identify this part of the code as the bottleneck?

**Comment by ZHG2017** [comment]
I submitted a lot of simulations on a cluster and found a few that did not finish in 48 hours. I then picked up one simulation with all its config files and landscapes files, I locally keep running it with some timing code inserted in the package. Then I found out the ecology_loop function becomes slower and slower, I then put more timing instructions in that function to figure out which lines are the cause. If we keep running the package for the evol simulation 12420 provided by [ohagen](https://github.com/ohagen), the current implementation will become slower at each iteration, after 200 iterations, you will the concerned code segment will take up to 40 seconds. The total runtime becomes bigger at each step, that's how I figured out this as a bottleneck. WIth the modified implementation, the simulation will not become too slower, at step 200th, the concerned code  with modification only takes about 6 seconds. By the way, I compared also the resulting species plots generated at each iteration between the current implementation and the modified one, I see no difference.

**Comment by benj919** [comment]
Also you can check the objects to themself before and after applying the function:
```
> identical(data$all_species, test(data))
[1] TRUE
> identical(data$all_species, test2(data))
[1] FALSE
```

**Review by ohagen — CHANGES_REQUESTED** [review]
@ZHG2017 , I forwarded @benj919 the last optimization report you sent me, which might contain some hints to the question he asked. I will merge this after @benj919  questions are replied.
@benj919, I will add an further issue if you think that adding the tests that @ZHG2017 developed could be handy for out checking routine.

**Comment by benj919** [comment]
For optimized code please ensure that the results are bitwise identical to the previous results. Unless there is a proven reason to have the code change the result. 

For identifying bottlenecks please familiarize yourself with the profiling functions in R. To get a reliable overview on what's going on.

I have forwarded @ohagen  the scripts I used during the initial optimizations to check for correctness and a calling script with optparse that has a switch available to enable and run the profiling data collection.

**Comment by ohagen** [comment]
thanks @benj919! I will FW this to @ZHG2017

**Comment by ZHG2017** [comment]
I don't think I could use any script to identify the bottleneck because the concerned simulation will last for more than 48 hours that I have never waited until its end to identify this bottleneck. At the moment, I have no idea how to have the bitwise identical result as previous one. So the issue becomes either we do not have the bitwise identical result or abandon those slow simulations.

**Comment by benj919** [comment]
You don't need those simulations to finish to start looking for trends. You can stop them after 48h and evaluate the profiling traces already. How many time steps did those simulations finish in 48hrs? Out of those how many hours were spent in the above optimized code fragment?

We know that simulations with many species have an escalating cost associated with them. That's why we originally implemented those abort conditions on too many species being alive.

You should get the code for the bitwise comparison results from ohagen soon.

**Comment by ZHG2017** [comment]
Let me provide a bit more details, there is a folder for the config files(more than one file inside), there is another folder for the landscape files(more than one file inside), the R script will use both folders for one specific simulation. My question is then how could we benchmark this simulation that will never finish ?

**Comment by benj919** [comment]
By not finishing it. The logfiles should tell you roughly how many timesteps a simulation can finish within 48hrs. By adjusting either the start or end timestep you can limit the simulation to run for a shorter amount of time. Or you just abort the simulation after 48hrs and compare the partial outputs. 

Once you have identified and optimized the bottlenecks present in those partial runs you can repeat the process and progress further into the simulation in 48hrs. Depending on the input size you should be able to figure out the trends within 12hrs or even shorter runs already.

**Comment by ZHG2017** [comment]
I need to mention more details, keep running this simulation locally, we could see that at each step, the simulation runs slower than previous step, the printed out timing I ever used shows that, the only code segment that will increase its runtime at each step is the one I tried to improve. And locally, I could see obvious speedup with the modification, so I wonder what would be the necessity to run another benchmark for identification of bottleneck.

**Comment by benj919** [comment]
You need to show the overall behaviour of the code. If the simulation gets slower with every time step the base assumption is that every piece of code gets slower. The interesting part is which piece gets disproportionally slower. For that you need to either do the profiling, or if you want to go with the timing you need to fully time all the major parts of the code. One you have that information you can, for example  runtime vs time step, where every bar is split into the time per component/function.  Do you have graphs for this showing the behaviour of all code parts?

If this is the only code segment that gets slower the simulation would have to go through ~4000+ time steps at 40sec/iteration?

Rprof can be used to profile by code line as well, which usually promotes the high level functions to the top of the list; Rprof(..., line.profiling = TRUE) and summaryRprof(..., lines="show"). I agree that it shows a lot of things, but they are needed to decide on what is actually important and what is not.

**Comment by ZHG2017** [comment]
Hi, I have got another question, I have just tried the following code:
```
  species_list <- list()
  for (species in data$all_species) {
    cells <- names(species[["abundance"]])[species[["abundance"]] != 0]
    updated_species <- limit_species_to_cells(species, cells)
    species_list <- append(species_list, list(updated_species))
  }

cat("----View(species_list)---->", View(species_list), "\n")
```
But got an error like the following:
```
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"gen3sis_species"’ to a data.frame
Calls: run_simulation ... <Anonymous> -> as.data.frame -> as.data.frame.default
```
So I wonder how could I get all the attributs of species_list either using View() or anything else ?

**Comment by benj919** [comment]
here's a one-line lapply implementation that preserves the attributes:
```
test3 <- function(data) {
  species_list <- lapply(data$all_species, function(i){limit_species_to_cells(i, names(i[["abundance"]])[i[["abundance"]] != 0])})
  return(species_list)
}

> microbenchmark(test(data), test2(data), test3(data), times = 10)
Unit: milliseconds
        expr      min       lq     mean   median       uq      max neval
  test(data) 457.5162 575.8027 695.6613 688.5292 840.1387 997.7278    10
 test2(data) 337.8429 379.9543 466.8935 421.4749 491.9027 874.7930    10
 test3(data) 286.2038 302.7601 352.8637 365.8548 386.3862 429.8704    10

> identical(data$all_species, test3(data))
[1] TRUE
```

View() is an interactive function that can't usually be printed. the outer species_list is just a list, you can get the attributes of elements in it with the attributes function:

```
> attributes(data$all_species[[1]])
$names
[1] "id"         "abundance"  "traits"     "divergence"

$class
[1] "gen3sis_species"
```

that can be `print(attributes(data$all_species[[1]]))`'ed but not be `cat()`'ed.

**Comment by ZHG2017** [comment]
> 

OK, I see, thank you ! Let me run  a partial benchmark locally to see if it still works. I did not know this syntax, I need to learn more syntax about R later.

**Comment by ZHG2017** [comment]
> on the View error, are you using Rstudio? View() is very helpful for manually/visually inspecting elements. As is the environment browser it offers.

Oh, I see. In fact, I used the command Rscript to launch the code,  I do not use Rstudio or any IDE.

**Comment by ZHG2017** [comment]
The runtime looks good:
step = 1914 , species alive = 2002 , species total = 15377 
------>length(data$all_species): 15681 
------>The for loop at the end of loop_ecology() took: 4.048102 
------>The for loop2 at the end of loop_ecology() took: 0.8134422 
I ran the timing for the current implementation as the first timing message then another timing is for the optimized one, I keep both implementations in the same script just to compare the 2 implementations.

**Comment by ZHG2017** [comment]
Hi [benj919](https://github.com/benj919), I did a few plots checking as well as bitwise species_list checking between the current implementation and the improved one using identical(), so I have adopted your suggested modification and pushed again for merging. Thank you for the suggested modification to get bitwise correctness !

**Comment by ohagen** [comment]
Thanks @benj919 and @ZHG2017 ! I guess we are now bitwise \o/ I am going ahead.

**Pull request merged**
