### PR TITLE
Add GitHub Actions CI

### LINKED ISSUE #49: implement CI
previously relying on Travis, now we need another solution. Specially if we want to improve collaboration

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Here it is: a Pull Request to add GitHub Actions CI to this repo, which fixes #49 . 

You can see the run pass at [here](https://github.com/richelbilderbeek/R-package/actions/runs/963164666). After acceptance of this PR, you can find results [here, at the Actions tab](https://github.com/project-gen3sis/R-package/actions).

This is all I did:

 * I added a default GitHub Actions script by doing `usethis::use_github_actions`, output with harmless warnings below.
 * I added `markdown` as a `Suggest`ed package in `DESCRIPTION`. This is needed nowadays when using vignettes

```r
✓ Setting active project to '/home/richel/GitHubs/R-package'
✓ Creating '.github/'
✓ Adding '^\\.github$' to '.Rbuildignore'
✓ Adding '*.html' to '.github/.gitignore'
✓ Creating '.github/workflows/'
✓ Writing '.github/workflows/R-CMD-check.yaml'
• Learn more at <https://github.com/r-lib/actions/blob/master/examples/README.md>
Error: Unsupported GitHub remote configuration: 'fork_upstream_is_not_origin_parent'
* Host = 'https://github.com'
* origin = 'richelbilderbeek/R-package' (can push) = fork of 'project-gen3sis/R-package'
* upstream = <not configured>
* The 'origin' GitHub remote is a fork, but its parent is not configured as the 'upstream' remote.

Read more about the GitHub remote configurations that usethis supports at:
'https://happygitwithr.com/common-remote-setups.html'
Run `rlang::last_error()` to see where the error occurred.
```

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
I should have worked on develop. I will close this PR and create a new fresh one :-)

**Comment by richelbilderbeek** [comment]
Reopened as @florianhartig [thinks that pushing to main is fine](https://github.com/project-gen3sis/R-package/issues/49#issuecomment-866641867).

**Comment by florianhartig** [comment]
Looks fine to me! Good idea with the contributing.md!

**Comment by florianhartig** [comment]
Many thanks, Richel!

**Comment by richelbilderbeek** [comment]
@florianhartig thanks so much for accepting that help, [from my experience, that is quite rare](https://github.com/richelbilderbeek/reports#reports)!

**Comment by richelbilderbeek** [comment]
@florianhartig are we good to merge this? This is just a friendly reminder: sometimes I forget to push the big green 'Merge' button myself as well :-)

**Comment by florianhartig** [comment]
I wanted to let @benj919 or @ohagen merge, I just gave my opinion that it looks good to me!

**Pull request merged**
